apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: l32duh0un-python 
  janus-idp.io/tekton: l32duh0un-python
  backstage.io/kubernetes-id: l32duh0un-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: l32duh0un-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml