apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l32duh0un-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l32duh0un-python 
  name: l32duh0un-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: l32duh0un-python 
